"""Auto-setup: bootstrap store_layout.json and data/staff_gallery from scratch.

The brief notes that faces are masked, so any classifier MUST be uniform-based.
This script runs once at pipeline start to ensure:

  1. `data/store_layout.json` exists. If missing, a coarse default is written
     from discovered camera clips + the floor plan zone names. Brand-level
     polygons require manual calibration (camera homography) and are NOT
     auto-generated here — see DESIGN.md §3.7.

  2. `data/staff_gallery/` is populated. If empty, we run YOLO+ByteTrack on
     each in-store camera, compute ResNet50 embeddings per track, DBSCAN
     cluster them, identify the largest visually-coherent cluster (the
     uniform group), and save its most-central crops as the staff gallery.
     Customers are everyone NOT matching this gallery — no customer
     gallery is needed.

The clustering rests on one assumption: **staff wear similar uniforms,
customers wear varied clothes.** With ResNet50 ImageNet features, tracks of
people in the same uniform cluster very tightly (cosine distance < 0.30);
customers form singletons or tiny clusters. DBSCAN's noise points + small
clusters are not staff.

Usage:
    python -m pipeline.auto_setup --layout /data/store_layout.json \\
        --footage /data/footage --gallery /data/staff_gallery

If both layout and gallery exist already, auto_setup is a no-op.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np


def _list_clips(footage_dir: Path) -> list[tuple[str, Path]]:
    """Discover (camera_id, clip_path) pairs from `CAM N.mp4` filenames."""
    out = []
    for f in sorted(footage_dir.iterdir()):
        if not f.is_file() or f.suffix.lower() not in (".mp4", ".mov", ".avi"):
            continue
        name = f.stem
        # 'CAM 1', 'CAM 2', etc.
        parts = name.replace(" ", "_").split("_")
        for p in parts:
            if p.isdigit():
                out.append((f"CAM_{int(p):02d}", f))
                break
    return out


DEFAULT_ZONE_PER_VIEW = {
    "FLOOR": "FLOOR",
    "ENTRY": "",
    "BACK_OFFICE": "BACK_OFFICE",
    "BILLING": "BILLING_QUEUE",
}


def write_default_layout(footage_dir: Path, out_path: Path, store_id: str = "STORE_001") -> dict:
    """Write a coarse default layout. Each camera gets ONE zone covering most
    of the frame (a 50px border is left out). Heuristic role assignment by
    camera number: CAM_03=ENTRY, CAM_04=BACK_OFFICE, CAM_05=BILLING, others=FLOOR.
    """
    clips = _list_clips(footage_dir)
    if not clips:
        raise RuntimeError(f"auto_setup: no clips found under {footage_dir}")

    cameras = []
    for camera_id, clip_path in clips:
        idx = int(camera_id.split("_")[1])
        if idx == 3:
            view = "ENTRY"
        elif idx == 4:
            view = "BACK_OFFICE"
        elif idx == 5:
            view = "BILLING"
        else:
            view = "FLOOR"

        cam = {
            "camera_id": camera_id,
            "view": view,
            "clip_path": f"{footage_dir.name}/{clip_path.name}",
            "zones": [],
        }
        if view == "ENTRY":
            # No zone on the entry cam; entry_line drives ENTRY/EXIT events.
            # The line position is a best-guess 5/8 across the frame width;
            # an operator should override this after viewing the clip.
            cam["entry_line"] = [[1100, 50], [1100, 1050]]
            cam["entry_normal_inward"] = [-1, 0]
        elif view == "BACK_OFFICE":
            cam["force_staff"] = True
            cam["zones"] = [{"zone_id": "BACK_OFFICE",
                              "polygon": [[50, 50], [1870, 50], [1870, 1030], [50, 1030]]}]
        elif view == "BILLING":
            cam["zones"] = [{"zone_id": "BILLING_QUEUE",
                              "polygon": [[300, 200], [1100, 200], [1100, 1050], [300, 1050]]}]
        else:  # FLOOR
            zone_id = f"{camera_id}_FLOOR"
            cam["zones"] = [{"zone_id": zone_id,
                              "polygon": [[80, 100], [1850, 100], [1850, 1050], [80, 1050]]}]
        cameras.append(cam)

    layout = {
        "_note": ("Auto-generated by pipeline.auto_setup. Coarse default — "
                  "each camera gets one whole-frame zone. Brand-level zones "
                  "require manual calibration. Edit this file or replace it "
                  "with one derived from the store's floor plan."),
        "stores": [{
            "store_id": store_id,
            "open_hours": {"start": "10:00", "end": "22:00", "tz": "Asia/Kolkata"},
            "cameras": cameras,
        }]
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(layout, indent=2))
    return layout


# ---------- staff gallery auto-discovery ----------

def _knn_eps(X: np.ndarray, k: int = 4) -> float:
    """Data-driven DBSCAN eps (median k-th nearest-neighbour distance) so the
    staff-cluster discovery adapts to the active embedding backend's distance
    scale instead of a magic number tuned for one model."""
    n = X.shape[0]
    if n <= k + 1:
        return 0.30
    D = 1.0 - X @ X.T
    np.fill_diagonal(D, np.inf)
    kth = np.partition(D, k, axis=1)[:, k]
    return min(0.5, max(0.05, float(np.median(kth))))


def _dbscan(X: np.ndarray, eps: float, min_samples: int) -> np.ndarray:
    """Lightweight DBSCAN on unit-norm vectors using cosine distance.
    Returns labels: -1 for noise, 0..K-1 for clusters.
    """
    n = X.shape[0]
    # Pairwise cosine distance.
    D = 1.0 - X @ X.T
    np.fill_diagonal(D, 0.0)

    labels = np.full(n, -1, dtype=int)
    visited = np.zeros(n, dtype=bool)
    cluster_id = 0

    def neighbours(i):
        return np.where(D[i] <= eps)[0]

    for i in range(n):
        if visited[i]:
            continue
        visited[i] = True
        N = neighbours(i)
        if len(N) < min_samples:
            labels[i] = -1
            continue
        labels[i] = cluster_id
        seeds = list(N)
        while seeds:
            j = seeds.pop()
            if not visited[j]:
                visited[j] = True
                Nj = neighbours(j)
                if len(Nj) >= min_samples:
                    seeds.extend(int(k) for k in Nj if not visited[k])
            if labels[j] == -1:
                labels[j] = cluster_id
        cluster_id += 1
    return labels


def auto_staff_gallery(crops_dirs: list[Path], gallery_dir: Path,
                       eps: float | None = None, min_samples: int = 4,
                       max_crops_in_gallery: int = 10) -> dict:
    """Discover staff via unsupervised clustering + save the largest
    visually-coherent cluster as the staff gallery. Uses the shared person
    embedder (OSNet re-ID, ResNet50 fallback); eps is data-driven by default.
    """
    from .reid import get_embedder

    # Collect crop paths.
    paths = []
    for d in crops_dirs:
        if d.is_dir():
            paths.extend(sorted(d.glob("*.jpg")))
    if not paths:
        return {"error": "no crops to cluster"}

    embedder = get_embedder()
    if not embedder.available:
        return {"error": "no embedding backend available (torch missing)"}
    X = np.vstack([embedder.embed_path(p) for p in paths])

    # Data-driven eps (k-distance heuristic) unless explicitly overridden, so
    # discovery adapts to the embedding backend's distance scale.
    if eps is None or eps <= 0:
        eps = _knn_eps(X, k=min_samples)
    labels = _dbscan(X, eps=eps, min_samples=min_samples)
    sizes = Counter(int(l) for l in labels if l >= 0)
    if not sizes:
        return {"error": "no cluster met min_samples; uniform may be heterogeneous "
                         "or footage too short. Lower min_samples or eps."}

    # Largest non-noise cluster = staff group.
    staff_cluster = max(sizes, key=lambda k: sizes[k])
    staff_idxs = np.where(labels == staff_cluster)[0]
    Xs = X[staff_idxs]
    centroid = Xs.mean(axis=0)
    centroid /= (np.linalg.norm(centroid) or 1.0)

    # Pick crops closest to centroid as the gallery representatives.
    sims = Xs @ centroid
    pick = staff_idxs[np.argsort(-sims)[:max_crops_in_gallery]]

    gallery_dir.mkdir(parents=True, exist_ok=True)
    saved = []
    for rank, i in enumerate(pick):
        src = paths[i]
        dst = gallery_dir / f"staff_auto_{rank:02d}_{src.stem}.jpg"
        shutil.copy(src, dst)
        saved.append(dst.name)

    return {
        "embedding_backend": embedder.backend,
        "eps_used": round(float(eps), 4),
        "clustered_tracks": int(len(paths)),
        "clusters_found": len(sizes),
        "cluster_sizes": dict(sizes),
        "staff_cluster_id": int(staff_cluster),
        "staff_cluster_size": int(sizes[staff_cluster]),
        "noise_tracks": int(sum(1 for l in labels if l < 0)),
        "gallery_dir": str(gallery_dir),
        "gallery_size": len(saved),
        "saved": saved,
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--layout", type=Path, default=Path("/data/store_layout.json"))
    p.add_argument("--footage", type=Path, default=Path("/data/footage"))
    p.add_argument("--gallery", type=Path, default=Path("/data/staff_gallery"))
    p.add_argument("--crops-dirs", nargs="+", type=Path,
                   default=[Path("/events/track_crops/CAM_01"),
                            Path("/events/track_crops/CAM_02"),
                            Path("/events/track_crops/CAM_05")])
    p.add_argument("--store-id", default="STORE_001")
    p.add_argument("--force", action="store_true",
                   help="Regenerate layout and gallery even if they exist.")
    p.add_argument("--eps", type=float, default=-1.0,
                   help="DBSCAN eps for staff-cluster discovery. Negative "
                        "(default) = derive from data (k-distance heuristic), "
                        "adapting to the active embedding backend.")
    p.add_argument("--min-samples", type=int, default=4)
    args = p.parse_args()

    summary: dict = {}

    if args.force or not args.layout.exists():
        print(f"auto_setup: generating default layout at {args.layout}", file=sys.stderr)
        try:
            write_default_layout(args.footage, args.layout, args.store_id)
            summary["layout"] = "generated"
        except Exception as e:
            summary["layout_error"] = str(e)
    else:
        summary["layout"] = "exists; skipped"

    gallery_empty = not args.gallery.exists() or not list(args.gallery.glob("*.jpg"))
    if args.force or gallery_empty:
        print(f"auto_setup: discovering staff cluster -> {args.gallery}", file=sys.stderr)
        result = auto_staff_gallery(args.crops_dirs, args.gallery,
                                    eps=args.eps, min_samples=args.min_samples)
        summary["gallery"] = result
    else:
        summary["gallery"] = f"exists ({len(list(args.gallery.glob('*.jpg')))} crops); skipped"

    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
